### ISSUE TITLE
Keine Ausgabe

### ISSUE THREAD

**Issue by skerbis** [factorylabs/redaxo_socialhub#1]
Hallo bei mir erhalte ich in der Ausgabe nur: 

timeline --
TIMELINE FB

Ausgabecode
REX_SOCIAL[type=timeline limit=50 from=facebook template=false]

Im Backend sind die Einträge sichtbar

**Comment by Sioweb** [comment]
Ho! Danke stimmt

Ich hab jetzt einen einfachen Output dafür generiert, ohne BIlder oder sowas, aber die Hashtags und Links werden verlinkt.

**Comment by skerbis** [comment]
hmmm .... habe es gerade installiert mit folgendem Ergebnis
![bildschirmfoto 2016-02-12 um 08 55 41](https://cloud.githubusercontent.com/assets/791247/13001476/88780f1c-d166-11e5-920f-d44928738e55.png)

**Comment by Sioweb** [comment]
Es kann jetzt natürlich sein, dass noch min. ein Plugin installiert werden muss. Hast du das?

**Comment by skerbis** [comment]
Ah ... ich Dummerchen. Ich denke es würde Sinn machen, da eine Meldung zu hinterlegen.

**Comment by Sioweb** [comment]
Das ist richtig. Bau ich ein Danke! 
Ich denke auch das eine Hilfe-Datei durchaus Sinn machen würde, sobald ich mal wieder Zeit hab, bau ich das ein.

**Comment by skerbis** [comment]
Kann man die geladenen Posts wieder zurücksetzen? Habe mal testweise unseren eigenen Stream angegeben.

**Comment by skerbis** [comment]
Über der Ausgabe gibt der mir ein "timeline --" aus.  Sonst klappt die Ausgabe
