### ISSUE TITLE
Addon unfertig!

### ISSUE THREAD

**Issue by georgkaser** [factorylabs/redaxo_socialhub#2]
Vielleicht sollte man das Addon erst fertigstellen bevor man es im Installer veröffentlicht. Denke Lorem Ipsum im Hilfetext verschreckt vielleicht neue User. 

<img width="1126" alt="bildschirmfoto 2016-01-25 um 15 25 16" src="https://cloud.githubusercontent.com/assets/6472869/12553465/0174797a-c378-11e5-927b-c6a8e03f9a4c.png">

Ansonsten finde ich die Idee gut.

**Comment by dergel** [comment]
Bei mir wird, sobald ich z.b. facebook installiere, irgendwo eine weiterleitung eingeschaltet, so dass ich mich nicht mehr ins backend einloggen kann. dann hilft nur noch socialhub ordner löschen .. 
@Sioweb Kannst Du das Addon erstmal offline nehmen ?

**Comment by Sioweb** [comment]
Die Hilfeseite ist weg. Danke die hatte ich aus den Augen verloren.
@dergel Ich kann das nicht reproduzieren, also eher nein.
